//C++

/*
----------------------------------------------------
The Desktop Project
------------------

Copyright 2004 Daher Alfawares

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

----------------------------------------------------
*/

#ifndef ___DGL_H
#define ___DGL_H



#include "DShared.h"

// DGL main
#include "DGL_Main.h"

// DGL utilities
#include "DGL_Texture.h"
#include "DGL_Frustum.h"
#include "DGL_Extensions.h"

// basic
#include "DGL_Color.h"
#include "DGL_Vertex.h"
#include "DGL_Matrix.h"
#include "DGL_Light.h"
#include "DGL_State.h"

// font
#include "DGL_Font.h"
#include "DGL_Font3D.h"

// effects
#include "DGL_FX.h"
#include "DGL_FadeScreen.h"
#include "DGL_Fog.h"
#include "DGL_Blur.h"
#include "DGL_Particle.h"
#include "DGL_Avi.h"
#include "DGL_TextImage.h"

// collision
#include "DGL_Ball.h"

// camera
#include "DGL_Camera.h"

// train
#include "DGL_Train.h"

// loading screen
#include "DGL_Loadingscreen.h"

// shader library
#include "DGL_Shader.h"

// models
#include "DGL_Model.h"	// base class
#include "DGL_Modelmilkshape.h"

// tomas hamala's model
#include "DGL_Tomas_Model.h" // base class
#include "DGL_Tomas_M3ds.h"

// terrain
#include "DGL_Terrain.h"
#include "DGL_Skybox.h"
#include "DGL_Water.h"


#endif // ___DGL_H